version: '3'

services:
  db:
    image: mysql:5.7.38
    container_name: 'nestjs-db'
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
